<!doctype html>
<html ng-app="Categorias">
    <head>
        <meta charset="UTF-8" />
        <title>ZF2 + Angular</title>
        <link href="css/bootstrap.min.css" media="screen" rel="stylesheet" />
    </head>
    <body>[
        <div id="wrap">
            <div class="navbar navbar-default navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toogle Navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">&nbsp;Zend + Angular</a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="/">Categorias</a></li>
                            <li><a href="/">Produtos</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="page-header" ng-controller="CategoriasCtrl">
                    <br />
                    <?php echo $this->content; ?>
                    <!-- cada uma dessas é uma diretiva. Ex: ng-view, ng-controller-->
                    <div ng-view></div>
                </div>
                <div id="footer">
                    <div class="container">
                        <p class="text-muted credit">Vinícius of NET</p>
                    </div>
                </div>
                <?php #echo $this->content; ?>
            </div>
            <?php echo $this->inlineScript() ?>
        </div>
        
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
        <script> var $jQuery = jQuery.noConflict(); </script>
        <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular.min.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular-route.min.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular-resource.min.js"></script>
        <script src="projetoangular/Categorias.js"></script>
        <script src="projetoangular/CategoriasCtrl.js"></script>
        <script src="projetoangular/CategoriasSrv.js"></script>
    </body>
</html>